# Generated by Django 5.2.7 on 2025-10-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_fielddivision_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddivision',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
